window.WorkspaceGames = (() => {
  let active;
  const core = window.WorkspaceGameCore;
  const W = 300;
  const H = 300;
  const E = (tag, className, text) => { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node; };
  const B = (text, handler) => { const node = E('button', '', text); node.type = 'button'; node.addEventListener('click', handler); return node; };
  const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
  const clone = (value) => JSON.parse(JSON.stringify(value));

  function shell(mount, title) {
    mount.textContent = '';
    const bar = E('div', 'game-bar'); const label = E('strong', '', title); bar.append(label); mount.append(bar);
    return { bar, label, stopped: false, clean: [] };
  }
  function dispose(game) { if (game.stopped) return; game.stopped = true; game.clean.splice(0).forEach((fn) => fn()); }
  function keyListener(game, callback) { const listener = (event) => callback(event, event.key.toLowerCase()); window.addEventListener('keydown', listener); game.clean.push(() => window.removeEventListener('keydown', listener)); }
  function canvas(game, width = W, height = H) { const node = E('canvas', 'game-canvas'); node.width = width; node.height = height; game.bar.after(node); return [node, node.getContext('2d')]; }

  function snake(mount, save, old) {
    const game = shell(mount, 'Snake'); const [, ctx] = canvas(game);
    let state = core.createSnakeState({ ...(old?.snapshot || {}), score: old?.score || 0 }), paused = false, speed = old?.snapshot?.speed || 130, initialLength = old?.snapshot?.initialLength || state.body.length;
    const persist = () => save({ score: state.score, best: Math.max(old?.best || 0, state.score), snapshot: { ...state, speed, initialLength } });
    const option = (label, entries, value, change) => { const wrap = E('label', 'game-option'); wrap.append(document.createTextNode(`${label} `)); const select = E('select'); entries.forEach(([text, optionValue]) => { const item = E('option', '', text); item.value = String(optionValue); item.selected = String(optionValue) === String(value); select.append(item); }); select.addEventListener('change', () => change(select.value)); wrap.append(select); return wrap; };
    const freshFood = () => {
      const head = { x: state.body[0].x + state.direction.x, y: state.body[0].y + state.direction.y };
      const occupied = [...state.body, head]; const free = [];
      for (let y = 0; y < state.height; y += 1) for (let x = 0; x < state.width; x += 1) if (!occupied.some((part) => part.x === x && part.y === y)) free.push({ x, y });
      return free.length ? free[Math.floor(Math.random() * free.length)] : undefined;
    };
    const draw = () => { ctx.fillStyle = '#151515'; ctx.fillRect(0, 0, W, H); ctx.fillStyle = '#9d9d9d'; state.body.forEach((part) => ctx.fillRect(part.x * 15 + 1, part.y * 15 + 1, 13, 13)); if (state.status === 'running') { ctx.fillStyle = '#d16969'; ctx.fillRect(state.food.x * 15 + 1, state.food.y * 15 + 1, 13, 13); } game.label.textContent = `Snake · ${state.score}${paused ? ' · Paused' : ''}${state.status === 'lost' ? ' · Game over' : state.status === 'won' ? ' · Cleared' : ''}`; };
    const reset = () => { state = core.createSnakeState({ wrap: state.wrap, initialLength }); paused = false; persist(); draw(); };
    const tick = () => { if (paused || state.status !== 'running' || game.stopped) return; const head = { x: state.body[0].x + state.direction.x, y: state.body[0].y + state.direction.y }; const ate = head.x === state.food.x && head.y === state.food.y; state = core.advanceSnake(state, ate ? freshFood() : undefined); if (state.status !== 'running') persist(); draw(); };
    keyListener(game, (event, key) => { const moves = { w: [0, -1], s: [0, 1], a: [-1, 0], d: [1, 0] }; if (moves[key]) { event.preventDefault(); const [x, y] = moves[key]; if (x !== -state.direction.x || y !== -state.direction.y) state.direction = { x, y }; } });
    let lastStep = 0; const timer = window.setInterval(() => { const now = Date.now(); if (!lastStep || now - lastStep >= speed) { lastStep = now; tick(); } }, 35); game.clean.push(() => { window.clearInterval(timer); persist(); }); game.bar.append(option('Wall', [['Off', 'off'], ['Wrap', 'wrap']], state.wrap ? 'wrap' : 'off', (value) => { state.wrap = value === 'wrap'; persist(); }), option('Speed', [['Slow', 190], ['Normal', 130], ['Fast', 85]], speed, (value) => { speed = Number(value); persist(); }), option('Length', [['1', 1], ['3', 3], ['5', 5], ['7', 7]], initialLength, (value) => { initialLength = Number(value); reset(); }), B('Pause', () => { paused = !paused; draw(); }), B('Restart', reset)); draw(); return { destroy: () => dispose(game) };
  }

  function flappy(mount, save, old) {
    const game = shell(mount, 'Flappy'); const [node, ctx] = canvas(game); let state = core.createFlappyState({ ...(old?.snapshot || {}), score: old?.score || 0 }), paused = false;
    const persist = () => save({ score: state.score, best: Math.max(old?.best || 0, state.score), snapshot: state }); const jump = () => { if (!paused && state.status === 'running') state.velocity = -6; };
    const reset = () => { state = core.createFlappyState(); paused = false; persist(); draw(); };
    const draw = () => { ctx.fillStyle = '#151515'; ctx.fillRect(0, 0, W, H); ctx.fillStyle = '#888'; state.pipes.forEach((pipe) => { ctx.fillRect(pipe.x, 0, 30, pipe.gap - 42); ctx.fillRect(pipe.x, pipe.gap + 42, 30, H); }); ctx.fillStyle = '#ddd'; ctx.beginPath(); ctx.arc(state.birdX, state.y, state.birdRadius, 0, Math.PI * 2); ctx.fill(); game.label.textContent = `Flappy · ${state.score}${paused ? ' · Paused' : ''}${state.status === 'lost' ? ' · Game over' : ''}`; };
    const timer = window.setInterval(() => { if (paused || state.status !== 'running' || game.stopped) return; state = core.advanceFlappy(state, { spawnGap: 65 + Math.random() * 130 }); if (state.status !== 'running') persist(); draw(); }, 30);
    keyListener(game, (event, key) => { if (key === 'w' || event.code === 'Space') { event.preventDefault(); jump(); } }); node.addEventListener('click', jump); game.clean.push(() => { window.clearInterval(timer); node.removeEventListener('click', jump); persist(); }); game.bar.append(B('Pause', () => { paused = !paused; draw(); }), B('Restart', reset)); draw(); return { destroy: () => dispose(game) };
  }

  function game2048(mount, save, old) {
    const game = shell(mount, '2048'); const board = E('div', 'board2048'); const saved = old?.snapshot || {}; const initial = { board: clone(saved.board || Array(16).fill(0)), score: old?.score || 0, status: saved.status || 'running' }; let history = saved.history || core.create2048History(initial), cells, score, status, undoButton, redoButton;
    const sync = () => { cells = clone(history.present.board); score = history.present.score; status = history.present.status; };
    const persist = () => save({ score, best: Math.max(old?.best || 0, score), snapshot: { board: cells, status, history } }); const add = (target) => { const free = target.map((value, index) => value ? -1 : index).filter((index) => index >= 0); if (free.length) target[free[Math.floor(Math.random() * free.length)]] = Math.random() < 0.9 ? 2 : 4; };
    const draw = () => { board.textContent = ''; cells.forEach((value) => board.append(E('div', 'tile', value || ''))); game.label.textContent = `2048 · ${score}${status === 'won' ? ' · 2048 reached' : status === 'lost' ? ' · Game over' : ''}`; if (undoButton) undoButton.disabled = !history.past.length; if (redoButton) redoButton.disabled = !history.future.length; };
    const commit = (next) => { history = core.commit2048History(history, next); sync(); persist(); draw(); };
    const reset = () => { const next = { board: Array(16).fill(0), score: 0, status: 'running' }; add(next.board); add(next.board); history = core.create2048History(next); sync(); persist(); draw(); };
    const move = (direction) => { if (status !== 'running') return; const result = core.move2048({ board: cells, score }, ['left', 'right', 'up', 'down'][direction]); if (!result.changed) { if (!core.has2048Moves(cells)) commit({ board: cells, score, status: 'lost' }); return; } const next = { board: result.state.board, score: result.state.score, status: 'running' }; add(next.board); if (next.board.some((value) => value >= 2048)) next.status = 'won'; else if (!core.has2048Moves(next.board)) next.status = 'lost'; commit(next); };
    keyListener(game, (event, key) => { const directions = { a: 0, d: 1, w: 2, s: 3 }; if (key in directions) { event.preventDefault(); move(directions[key]); } }); game.bar.after(board); undoButton = B('Undo', () => { history = core.undo2048History(history); sync(); persist(); draw(); }); redoButton = B('Redo', () => { history = core.redo2048History(history); sync(); persist(); draw(); }); game.bar.append(undoButton, redoButton, B('Continue', () => { if (status === 'won') commit({ board: cells, score, status: 'running' }); }), B('New', reset)); sync(); if (!cells.some(Boolean)) reset(); else draw(); game.clean.push(persist); return { destroy: () => dispose(game) };
  }

  function breakout(mount, save, old) {
    const game = shell(mount, 'Breakout'); const [node, ctx] = canvas(game); let state = core.createBreakoutState(old?.snapshot || {}), paused = false;
    const powers = { wide: ['W', 'Wide', 'good'], slow: ['S', 'Slow', 'good'], life: ['+', 'Life', 'good'], pierce: ['P', 'Pierce', 'good'], multi: ['M', 'Multi', 'good'], fast: ['F', 'Fast', 'bad'], shrink: ['−', 'Shrink', 'bad'], sticky: ['K', 'Sticky', 'good'] };
    const legend = E('div', 'breakout-legend'); Object.entries(powers).forEach(([type, [symbol, name, tone]]) => { const item = E('span', `power-${tone}`, `${symbol} ${name}`); item.title = type; legend.append(item); }); node.after(legend);
    const powerName = (type) => powers[type]?.[1] || type;
    const persist = () => save({ score: state.score, best: Math.max(old?.best || 0, state.score), snapshot: state }); const draw = () => { ctx.clearRect(0, 0, W, H); state.bricks.forEach((brick) => { ctx.fillStyle = brick.hp >= 3 ? '#8b6262' : brick.hp === 2 ? '#9a855a' : '#6f7884'; ctx.fillRect(brick.x, brick.y, brick.width, brick.height); if (brick.hp > 1 && ctx.fillText) { ctx.fillStyle = '#f0f0f0'; ctx.font = '10px sans-serif'; ctx.fillText(String(brick.hp), brick.x + 17, brick.y + 11); } }); state.powerUps.forEach((item) => { const visual = powers[item.type] || ['?', item.type, 'good']; ctx.fillStyle = visual[2] === 'bad' ? '#ad615d' : '#4f8369'; ctx.fillRect(item.x - 8, item.y - 7, 16, 14); if (ctx.fillText) { ctx.fillStyle = '#ffffff'; ctx.font = '10px sans-serif'; ctx.fillText(visual[0], item.x - 3, item.y + 4); } }); ctx.fillStyle = '#888'; ctx.fillRect(state.paddle.x, state.paddle.y, state.paddle.width, state.paddle.height); state.balls.forEach((ball) => { ctx.beginPath(); ctx.arc(ball.x, ball.y, ball.radius, 0, Math.PI * 2); ctx.fill(); }); const effects = [state.pierceHits ? `Pierce ${state.pierceHits}` : '', state.sticky ? `Sticky ${state.sticky}` : '', state.powerUps.length ? `Drop ${state.powerUps.map((item) => powerName(item.type)).join(', ')}` : '', state.balls.length > 1 ? `Balls ${state.balls.length}` : ''].filter(Boolean).join(' · '); game.label.textContent = `Breakout · ${state.score} · L${state.level}/${state.maxLevel} · Lives ${state.lives}${effects ? ` · ${effects}` : ''}${state.stuck ? ' · Ready (W/Space)' : ''}${paused ? ' · Paused' : ''}${state.status === 'won' ? ' · Complete' : state.status === 'lost' ? ' · Game over' : ''}`; };
    const reset = () => { state = core.createBreakoutState(); paused = false; persist(); draw(); }; const paddle = (amount) => { state.paddle.x = clamp(state.paddle.x + amount, 0, W - state.paddle.width); draw(); }; const release = () => { state = core.releaseBreakoutBall(state); draw(); };
    keyListener(game, (event, key) => { if (key === 'a') { event.preventDefault(); paddle(-18); } if (key === 'd') { event.preventDefault(); paddle(18); } if ((key === 'w' || event.code === 'Space') && state.stuck) { event.preventDefault(); release(); } }); const mouse = (event) => { const rect = node.getBoundingClientRect(); const pointerX = core.mapBreakoutPointer(event.clientX, rect.left, rect.width, W); state.paddle.x = clamp(pointerX - state.paddle.width / 2, 0, W - state.paddle.width); draw(); }; node.addEventListener('mousemove', mouse);
    const timer = window.setInterval(() => { if (game.stopped || paused || state.status !== 'running') return; state = core.advanceBreakout(state); if (state.status !== 'running') persist(); draw(); }, 25); game.clean.push(() => { window.clearInterval(timer); node.removeEventListener('mousemove', mouse); persist(); }); game.bar.append(B('Pause', () => { paused = !paused; draw(); }), B('Release', release), B('New Board', reset)); draw(); return { destroy: () => dispose(game) };
  }

  function tetris(mount, save, old) {
    const game = shell(mount, 'Tetris'); const [, ctx] = canvas(game, 200, 400); let state = core.createTetrisState(old?.snapshot || {}), paused = false;
    const persist = () => save({ score: state.score, best: Math.max(old?.best || 0, state.score), snapshot: state }); const draw = () => { ctx.clearRect(0, 0, 200, 400); const drawBlock = (x, y, color) => { ctx.fillStyle = color; ctx.fillRect(x * 20 + 1, y * 20 + 1, 18, 18); }; state.board.forEach((row, y) => row.forEach((cell, x) => { if (cell) drawBlock(x, y, '#888'); })); state.piece.shape.forEach((row, y) => row.forEach((cell, x) => { if (cell) drawBlock(state.piece.x + x, state.piece.y + y, '#ddd'); })); game.label.textContent = `Tetris · ${state.score} · Lines ${state.lines} · Lv ${state.level}${paused ? ' · Paused' : ''}${state.status === 'lost' ? ' · Game over' : ''}`; };
    const act = (action) => { if (!paused && state.status === 'running') { state = core.moveTetris(state, action); persist(); draw(); } }; const reset = () => { state = core.createTetrisState(); paused = false; persist(); draw(); };
    keyListener(game, (event, key) => { const moves = { a: 'left', d: 'right', s: 'down', w: 'rotate' }; if (moves[key]) { event.preventDefault(); act(moves[key]); } if (event.code === 'Space') { event.preventDefault(); act('drop'); } }); let fallElapsed = 0; const timer = window.setInterval(() => { if (paused || state.status !== 'running') return; fallElapsed += 50; if (fallElapsed >= Math.max(100, 550 - (state.level - 1) * 45)) { fallElapsed = 0; act('down'); } }, 50); game.clean.push(() => { window.clearInterval(timer); persist(); }); game.bar.append(B('Pause', () => { paused = !paused; draw(); }), B('Hard Drop', () => act('drop')), B('New', reset)); draw(); return { destroy: () => dispose(game) };
  }

  function mines(mount, save, old) {
    const game = shell(mount, 'Mines · 10 mines'); const board = E('div', 'mines'); let state = core.createMinesState(old?.snapshot || {}), selected = old?.snapshot?.selected || 0, started = old?.snapshot?.started || Date.now();
    const newMines = () => { const mineSet = new Set(); while (mineSet.size < 10) mineSet.add(Math.floor(Math.random() * 81)); return [...mineSet]; };
    const persist = () => save({ score: state.status === 'won' ? 1 : 0, best: Math.max(old?.best || 0, state.status === 'won' ? 1 : 0), snapshot: { ...state, selected, started } });
    const count = (index) => core.mineNeighbours(index, state.size).filter((value) => state.mines.includes(value)).length;
    const draw = () => { board.textContent = ''; const shown = new Set(state.revealed); const flags = new Set(state.flags); for (let index = 0; index < 81; index += 1) { const text = flags.has(index) ? '⚑' : shown.has(index) ? (state.mines.includes(index) ? '✕' : String(count(index) || '')) : ''; const cell = B(text, () => open(index)); cell.classList.toggle('selected', selected === index); cell.addEventListener('contextmenu', (event) => { event.preventDefault(); flag(index); }); board.append(cell); } game.label.textContent = `Mines · ${state.mineCount - state.flags.length} remaining · ${Math.floor((Date.now() - started) / 1000)}s${state.status === 'won' ? ' · Cleared' : state.status === 'lost' ? ' · Mine hit' : ''}`; };
    const reset = () => { state = core.createMinesState({ mines: newMines() }); selected = 0; started = Date.now(); persist(); draw(); };
    const open = (index) => { state = core.openMineCell(state, index); if (state.status !== 'running') persist(); draw(); };
    const flag = (index) => { state = core.toggleMineFlag(state, index); draw(); };
    const moveSelection = (delta) => { const row = Math.floor(selected / 9), column = selected % 9; if (delta === -9 && row) selected -= 9; if (delta === 9 && row < 8) selected += 9; if (delta === -1 && column) selected -= 1; if (delta === 1 && column < 8) selected += 1; draw(); };
    keyListener(game, (event, key) => { const moves = { w: -9, s: 9, a: -1, d: 1 }; if (key in moves) { event.preventDefault(); moveSelection(moves[key]); } if (event.code === 'Space' || key === 'enter') { event.preventDefault(); open(selected); } if (key === 'f') { event.preventDefault(); flag(selected); } }); const timer = window.setInterval(() => { if (state.status === 'running') draw(); }, 1000); game.clean.push(() => { window.clearInterval(timer); persist(); }); game.bar.after(board); game.bar.append(B('Restart', reset)); if (!state.mines.length) reset(); else draw(); return { destroy: () => dispose(game) };
  }

  function sudoku(mount) {
    const game = shell(mount, 'Sudoku'); const board = E('div', 'sudoku'); const puzzles = [{ name: 'Easy', puzzle: '530070000600195000098000060800060003400803001700020006060000280000419005000080079', solution: '534678912672195348198342567859761423426853791713924856961537284287419635345286179' }, { name: 'Medium', puzzle: '000260701680070090190004500820100040004602900050003028009300074040050036703018000', solution: '435269781682571493197834562826195347374682915951743628519326874248957136763418259' }]; let mode = 0, selected = 0, cells = [], values = Array(81).fill('');
    const allValues = () => puzzles[mode].puzzle.split('').map((value, index) => value === '0' ? values[index] : value);
    const applyConflicts = () => { const conflicts = new Set(core.sudokuConflictIndexes(allValues())); cells.forEach((cell, index) => cell.classList.toggle('bad', conflicts.has(index))); return conflicts; };
    const draw = () => { const data = puzzles[mode]; board.textContent = ''; cells = []; for (let index = 0; index < 81; index += 1) { const input = E('input', 'cell'); input.maxLength = 1; input.inputMode = 'numeric'; input.value = data.puzzle[index] === '0' ? values[index] : data.puzzle[index]; input.disabled = data.puzzle[index] !== '0'; input.classList.toggle('selected', selected === index); input.addEventListener('focus', () => { selected = index; }); input.addEventListener('input', () => { input.value = input.value.replace(/[^1-9]/g, '').slice(0, 1); values[index] = input.value; applyConflicts(); }); cells.push(input); board.append(input); } applyConflicts(); game.label.textContent = `Sudoku · ${data.name}`; };
    const moveSelection = (delta) => { const row = Math.floor(selected / 9), column = selected % 9; if (delta === -9 && row) selected -= 9; if (delta === 9 && row < 8) selected += 9; if (delta === -1 && column) selected -= 1; if (delta === 1 && column < 8) selected += 1; draw(); cells[selected]?.focus(); };
    keyListener(game, (event, key) => { const moves = { w: -9, s: 9, a: -1, d: 1 }; if (moves[key]) { event.preventDefault(); moveSelection(moves[key]); } }); const check = () => { const conflicts = applyConflicts(); const solved = allValues().join('') === puzzles[mode].solution; game.label.textContent = solved ? 'Sudoku · Solved' : conflicts.size ? 'Sudoku · Conflicts highlighted' : 'Sudoku · No conflicts'; }; const clear = () => { if (puzzles[mode].puzzle[selected] === '0') { values[selected] = ''; cells[selected].value = ''; applyConflicts(); } }; const next = () => { mode = (mode + 1) % puzzles.length; selected = 0; values = Array(81).fill(''); draw(); };
    game.bar.after(board); game.bar.append(B('Check', check), B('Clear', clear), B('New Puzzle', next)); draw(); return { destroy: () => dispose(game) };
  }

  function bubble(mount, save, old) {
    const game = shell(mount, 'Bubble'); const board = E('div', 'bubble'); let selected = old?.snapshot?.selected || 0, state = core.createBubbleState({ popped: old?.snapshot?.popped || [], count: old?.score || 0 });
    const persist = () => save({ score: state.count, best: Math.max(old?.best || 0, state.count), snapshot: { ...state, selected } }); const draw = () => { const popped = new Set(state.popped); board.textContent = ''; for (let index = 0; index < 64; index += 1) { const cell = B('', () => pop(index)); cell.classList.toggle('popped', popped.has(index)); cell.classList.toggle('selected', selected === index); board.append(cell); } game.label.textContent = `Bubble · ${state.count} popped`; }; const pop = (index) => { const before = state.count; state = core.popBubble(state, index); if (state.count !== before) persist(); draw(); }; const reset = () => { selected = 0; state = core.createBubbleState(); persist(); draw(); }; const moveSelection = (delta) => { const row = Math.floor(selected / 8), column = selected % 8; if (delta === -8 && row) selected -= 8; if (delta === 8 && row < 7) selected += 8; if (delta === -1 && column) selected -= 1; if (delta === 1 && column < 7) selected += 1; draw(); };
    keyListener(game, (event, key) => { const moves = { w: -8, s: 8, a: -1, d: 1 }; if (key in moves) { event.preventDefault(); moveSelection(moves[key]); } if (event.code === 'Space' || key === 'enter') { event.preventDefault(); pop(selected); } }); game.bar.after(board); game.bar.append(B('Reset', reset), B('Regenerate', reset)); game.clean.push(persist); draw(); return { destroy: () => dispose(game) };
  }

  return { start(name, mount, save, old) { if (active) active.destroy(); const games = { snake, flappy, '2048': game2048, breakout, tetris, mines, sudoku, bubble }; active = games[name] ? games[name](mount, save, old) : { destroy() {} }; return active; } };
})();
